<?php

/**
 * @file
 * Primary module hooks for Mellow Clo Credentials module.
 */

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function mellow_clo_credentials_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'system_powered_by_block') {
    $variables['content']['#markup'] .= '<div class="credentials">Identifiant: admin | Mot de passe: admin123</div>';
  }
}
