<?php

/**
 * @file
 * Primary module hooks for Mellow Clo Helper module.
 */
function mellow_clo_helper_theme(): array {
  return [
    'mellow_clo_helper_user_links_block_theme' => [
      'variables' => [
        'user_cart' => NULL,
        'user_account' => NULL,
      ],
    ],
    'mellow_clo_homepage_sliderblock' => [
      'variables' => [
        'slides' => NULL,
      ],
    ],
  ];
}


